In [1]:
import pandas as pd

In [2]:
#Read the csv file into a data frame
df = pd.read_csv('A2Z insurance.csv')
#print the first 5 rows of the data frame
df.head()

,Customer Identity,First Policy´s Year,Brithday Year,Educational Degree,Gross Monthly Salary,Geographic Living Area,Has Children (Y=1),Customer Monetary Value,Claims Rate,Premiums in LOB: Motor,Premiums in LOB: Household,Premiums in LOB: Health,Premiums in LOB: Life,Premiums in LOB: Work Compensations
0,1,1985.0,1982.0,2 - High School,2177.0,1.0,1.0,380.97,0.39,375.85,79.45,146.36,47.01,16.89
1,2,1981.0,1995.0,2 - High School,677.0,4.0,1.0,-131.13,1.12,77.46,416.20,116.69,194.48,106.13
2,3,1991.0,1970.0,1 - Basic,2277.0,3.0,0.0,504.67,0.28,206.15,224.50,124.58,86.35,99.02
3,4,1990.0,1981.0,3 - BSc/MSc,1099.0,4.0,1.0,-16.99,0.99,182.48,43.35,311.17,35.34,28.34
4,5,1986.0,1973.0,3 - BSc/MSc,1763.0,4.0,1.0,35.23,0.90,338.62,47.80,182.59,18.78,41.45

In [3]:
#shape of the dataset: 10296 rows, 14 columns
print(df.shape)
#name of columns
print(df.columns)

(10296, 14)
Index(['Customer Identity', 'First Policy´s Year', 'Brithday Year',
       'Educational Degree', 'Gross Monthly Salary', 'Geographic Living Area',
       'Has Children (Y=1)', 'Customer Monetary Value', 'Claims Rate',
       'Premiums in LOB: Motor', 'Premiums in LOB: Household',
       'Premiums in LOB: Health', 'Premiums in LOB:  Life',
       'Premiums in LOB: Work Compensations'],
      dtype='object')

In [4]:
df.info()
#It means we have null values, we have to replace them, otherwise the cluster won't work.
# The object type means string on this case, in this case it's the colunm Educational Degree

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10296 entries, 0 to 10295
Data columns (total 14 columns):
Customer Identity                      10296 non-null int64
First Policy´s Year                    10266 non-null float64
Brithday Year                          10279 non-null float64
Educational Degree                     10279 non-null object
Gross Monthly Salary                   10260 non-null float64
Geographic Living Area                 10295 non-null float64
Has Children (Y=1)                     10275 non-null float64
Customer Monetary Value                10296 non-null float64
Claims Rate                            10296 non-null float64
Premiums in LOB: Motor                 10262 non-null float64
Premiums in LOB: Household             10296 non-null float64
Premiums in LOB: Health                10253 non-null float64
Premiums in LOB:  Life                 10192 non-null float64
Premiums in LOB: Work Compensations    10210 non-null float64
dtypes: float64(12), int64(1), object(1)
memory usage: 1.1+ MB

In [5]:
df.describe()
#Give us some statistics about the data
#We can see that we don't have absurd data in here.
#Ex: we have 10296 rows, if the max on customer identity was bigger than this it will be something very wrong.

,Customer Identity,First Policy´s Year,Brithday Year,Gross Monthly Salary,Geographic Living Area,Has Children (Y=1),Customer Monetary Value,Claims Rate,Premiums in LOB: Motor,Premiums in LOB: Household,Premiums in LOB: Health,Premiums in LOB: Life,Premiums in LOB: Work Compensations
count,10296.00000,10266.000000,10279.000000,10260.000000,10295.000000,10275.000000,10296.000000,10296.000000,10262.000000,10296.000000,10253.000000,10192.000000,10210.000000
mean,5148.50000,1991.062634,1968.007783,2506.667057,2.709859,0.706764,177.892605,0.742772,300.470252,210.431192,171.580833,41.855782,41.277514
std,2972.34352,511.267913,19.709476,1157.449634,1.266291,0.455268,1945.811505,2.916964,211.914997,352.595984,296.405976,47.480632,51.513572
min,1.00000,1974.000000,1028.000000,333.000000,1.000000,0.000000,-165680.420000,0.000000,-4.110000,-75.000000,-2.110000,-7.000000,-12.000000
25%,2574.75000,1980.000000,1953.000000,1706.000000,1.000000,0.000000,-9.440000,0.390000,190.590000,49.450000,111.800000,9.890000,10.670000
50%,5148.50000,1986.000000,1968.000000,2501.500000,3.000000,1.000000,186.870000,0.720000,298.610000,132.800000,162.810000,25.560000,25.670000
75%,7722.25000,1992.000000,1983.000000,3290.250000,4.000000,1.000000,399.777500,0.980000,408.300000,290.050000,219.820000,57.790000,56.790000
max,10296.00000,53784.000000,2001.000000,55215.000000,4.000000,1.000000,11875.890000,256.200000,11604.420000,25048.800000,28272.000000,398.300000,1988.700000

In [6]:
fpy_outlier = df.loc[df['First Policy´s Year'] > 2016, ['First Policy´s Year']]
fpy_outlier

      First Policy´s Year
9294              53784.0

In [7]:
by_outlier = df.loc[df['Brithday Year'] < 1900, ['Brithday Year']]
by_outlier

      Brithday Year
7195         1028.0

In [8]:
age = 2016 - df['Brithday Year']
df = pd.concat((df, age.rename('Age')), axis=1)
df

,Customer Identity,First Policy´s Year,Brithday Year,Educational Degree,Gross Monthly Salary,Geographic Living Area,Has Children (Y=1),Customer Monetary Value,Claims Rate,Premiums in LOB: Motor,Premiums in LOB: Household,Premiums in LOB: Health,Premiums in LOB: Life,Premiums in LOB: Work Compensations,Age
0,1,1985.0,1982.0,2 - High School,2177.0,1.0,1.0,380.97,0.39,375.85,79.45,146.36,47.01,16.89,34.0
1,2,1981.0,1995.0,2 - High School,677.0,4.0,1.0,-131.13,1.12,77.46,416.20,116.69,194.48,106.13,21.0
2,3,1991.0,1970.0,1 - Basic,2277.0,3.0,0.0,504.67,0.28,206.15,224.50,124.58,86.35,99.02,46.0
3,4,1990.0,1981.0,3 - BSc/MSc,1099.0,4.0,1.0,-16.99,0.99,182.48,43.35,311.17,35.34,28.34,35.0
4,5,1986.0,1973.0,3 - BSc/MSc,1763.0,4.0,1.0,35.23,0.90,338.62,47.80,182.59,18.78,41.45,43.0
5,6,1986.0,1956.0,2 - High School,2566.0,4.0,1.0,-24.33,1.00,440.75,18.90,114.80,7.00,7.67,60.0
6,7,1979.0,1943.0,2 - High School,4103.0,4.0,0.0,-66.01,1.05,156.92,295.60,317.95,14.67,26.34,73.0
7,8,1988.0,1974.0,2 - High School,1743.0,4.0,1.0,-144.91,1.13,248.27,397.30,144.36,66.68,53.23,42.0
8,9,1981.0,1978.0,3 - BSc/MSc,1862.0,1.0,1.0,356.53,0.36,344.51,18.35,210.04,8.78,9.89,38.0
9,10,1976.0,1948.0,3 - BSc/MSc,3842.0,1.0,0.0,-119.35,1.12,209.26,182.25,271.94,39.23,55.12,68.0
10,11,1990.0,1945.0,3 - BSc/MSc,3995.0,4.0,0.0,290.17,0.53,296.50,116.70,227.71,18.67,10.89,71.0
11,12,1985.0,1958.0,3 - BSc/MSc,2834.0,3.0,1.0,405.74,0.46,249.49,216.70,252.38,36.34,35.45,58.0
12,13,1981.0,1949.0,3 - BSc/MSc,3757.0,1.0,0.0,2.34,0.97,206.04,340.05,257.05,43.12,15.78,67.0
13,14,1983.0,2000.0,1 - Basic,1043.0,3.0,1.0,-75.12,1.06,44.34,342.85,127.69,267.94,94.46,16.0
14,15,1983.0,1975.0,2 - High School,1981.0,1.0,1.0,-89.00,1.12,504.43,-70.00,72.79,10.89,16.89,41.0
15,16,1988.0,1979.0,3 - BSc/MSc,974.0,4.0,1.0,290.06,0.53,318.06,93.90,247.49,-3.00,19.67,37.0
16,17,1991.0,1989.0,2 - High School,2437.0,1.0,1.0,100.58,0.89,119.80,647.35,168.92,125.58,37.23,27.0
17,18,1981.0,1970.0,3 - BSc/MSc,2728.0,4.0,1.0,78.91,0.85,446.64,107.80,86.35,3.89,27.56,46.0
18,19,1981.0,1982.0,1 - Basic,1414.0,3.0,1.0,230.38,0.71,313.17,373.40,121.80,14.78,72.57,34.0
19,20,1988.0,1962.0,4 - PhD,2751.0,1.0,1.0,352.96,0.36,402.41,9.45,125.69,24.45,30.56,54.0
20,21,1986.0,1986.0,4 - PhD,1704.0,4.0,1.0,373.73,0.39,329.84,65.00,221.93,3.89,33.34,30.0
21,22,1977.0,1958.0,2 - High School,NaN,3.0,1.0,111.37,0.80,407.52,111.70,100.13,24.67,30.34,58.0
22,23,1976.0,1986.0,2 - High School,1495.0,1.0,1.0,-89.79,1.08,209.04,308.95,192.48,64.79,54.90,30.0
23,24,1998.0,1961.0,2 - High School,2870.0,4.0,1.0,290.05,0.64,222.04,329.50,248.38,48.01,33.56,55.0
24,25,1988.0,1952.0,3 - BSc/MSc,3201.0,4.0,0.0,108.13,0.81,420.30,128.35,135.58,15.67,4.78,64.0
25,26,1974.0,1944.0,4 - PhD,3776.0,2.0,0.0,376.30,0.41,383.74,103.90,154.14,17.56,15.78,72.0
26,27,1978.0,1937.0,4 - PhD,4281.0,3.0,0.0,430.86,0.38,330.84,162.80,228.82,-5.00,22.78,79.0
27,28,1979.0,1942.0,4 - PhD,3619.0,1.0,0.0,-7.22,0.97,449.75,58.90,112.91,17.78,9.78,74.0
28,29,1995.0,1952.0,3 - BSc/MSc,3639.0,4.0,0.0,264.17,0.50,301.28,18.90,258.05,-4.00,-0.11,64.0
29,30,1980.0,1972.0,3 - BSc/MSc,2660.0,3.0,0.0,2.00,0.96,524.21,25.00,54.90,7.00,-5.00,44.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10266,10267,1982.0,1937.0,2 - High School,3694.0,4.0,0.0,649.90,0.25,269.94,378.40,187.37,33.34,26.56,79.0
10267,10268,1977.0,1996.0,1 - Basic,834.0,4.0,1.0,254.72,0.67,181.48,309.50,134.58,114.80,98.24,20.0
10268,10269,1987.0,1988.0,3 - BSc/MSc,1414.0,3.0,1.0,50.46,0.90,129.58,167.80,184.48,165.92,75.46,28.0
10269,10270,1990.0,1976.0,2 - High School,1858.0,1.0,1.0,-207.91,1.34,175.59,-40.55,256.16,142.36,11.00,40.0
10270,10271,1978.0,1968.0,3 - BSc/MSc,2850.0,1.0,1.0,497.55,0.08,550.66,-15.00,25.45,4.00,1.89,48.0
10271,10272,1978.0,1961.0,3 - BSc/MSc,2740.0,1.0,1.0,431.10,0.19,460.31,-6.10,92.35,1.89,16.67,55.0
10272,10273,1978.0,1946.0,3 - BSc/MSc,3443.0,4.0,0.0,-35.89,1.02,326.73,142.80,207.26,10.89,20.56,70.0
10273,10274,1989.0,1992.0,2 - High School,1035.0,1.0,1.0,293.51,0.58,235.71,195.60,103.13,170.92,58.12,24.0
10274,10275,1995.0,1990.0,3 - BSc/MSc,1729.0,2.0,1.0,-58.78,1.06,187.59,28.90,295.61,33.34,62.68,26.0
10275,10276,1987.0,1959.0,3 - BSc/MSc,2512.0,4.0,1.0,577.23,0.24,361.29,254.50,95.35,48.01,34.45,57.0
10276,10277,1991.0,1983.0,3 - BSc/MSc,1791.0,3.0,1.0,281.06,0.54,308.06,122.80,215.82,-2.00,27.56,33.0
10277,10278,1997.0,1984.0,4 - PhD,1078.0,4.0,0.0,231.94,0.66,266.94,211.70,215.93,39.34,29.34,32.0
10278,10279,1989.0,1962.0,3 - BSc/MSc,3034.0,1.0,1.0,567.55,0.03,552.55,40.00,16.56,1.00,1.89,54.0
10279,10280,1978.0,1977.0,2 - High School,1404.0,3.0,1.0,-66.12,1.06,280.94,176.15,196.48,41.12,32.23,39.0
10280,10281,1975.0,1961.0,3 - BSc/MSc,2821.0,4.0,1.0,-24.22,1.00,468.20,19.45,90.46,18.67,9.78,55.0
10281,10282,1996.0,1945.0,2 - High School,3670.0,3.0,1.0,-54.67,1.04,381.96,167.80,148.25,7.78,37.45,71.0
10282,10283,1996.0,1974.0,3 - BSc/MSc,1868.0,3.0,1.0,-16.00,0.99,417.08,108.90,133.47,4.78,13.78,42.0
10283,10284,1992.0,1979.0,2 - High School,1219.0,4.0,1.0,211.60,0.60,236.60,18.35,162.81,76.57,90.35,37.0
10284,10285,1980.0,1987.0,3 - BSc/MSc,1504.0,4.0,1.0,-1.55,0.96,390.63,29.45,179.70,-6.00,NaN,29.0
10285,10286,1985.0,1948.0,3 - BSc/MSc,3878.0,4.0,1.0,-57.45,1.04,269.05,217.25,219.93,32.45,NaN,68.0
10286,10287,1997.0,1943.0,3 - BSc/MSc,3975.0,2.0,0.0,220.27,0.62,285.61,77.25,241.49,31.45,8.89,73.0
10287,10288,1996.0,1941.0,2 - High School,3845.0,4.0,0.0,99.47,0.90,87.35,843.50,121.58,157.92,33.45,75.0
10288,10289,1982.0,1993.0,2 - High School,1465.0,1.0,1.0,795.15,0.35,67.79,820.15,102.13,182.48,86.46,23.0
10289,10290,1986.0,1943.0,2 - High School,3498.0,4.0,0.0,245.60,0.67,227.82,270.60,160.92,100.13,69.90,73.0
10290,10291,1994.0,1999.0,1 - Basic,626.0,3.0,1.0,176.26,0.85,6.89,878.50,103.13,113.02,201.26,17.0
10291,10292,1984.0,1949.0,4 - PhD,3188.0,2.0,0.0,-0.11,0.96,393.74,49.45,173.81,9.78,14.78,67.0
10292,10293,1977.0,1952.0,1 - Basic,2431.0,3.0,0.0,1405.60,0.00,133.58,1035.75,143.25,12.89,105.13,64.0
10293,10294,1994.0,1976.0,3 - BSc/MSc,2918.0,1.0,1.0,524.10,0.21,403.63,132.80,142.25,12.67,4.89,40.0
10294,10295,1981.0,1977.0,1 - Basic,1971.0,2.0,1.0,250.05,0.65,188.59,211.15,198.37,63.90,112.91,39.0
10295,10296,1990.0,1981.0,4 - PhD,2815.0,1.0,1.0,463.75,0.27,414.08,94.45,141.25,6.89,12.89,35.0

In [9]:
nonsense_gms = df.loc[df['Age'] < 16, 'Gross Monthly Salary']
nonsense_gms

659     1284.0
689     1180.0
865      562.0
1436     823.0
2579    1006.0
3146     372.0
4465     958.0
4483    1241.0
5347    1119.0
5607    1131.0
8962    1117.0
9906    1422.0
Name: Gross Monthly Salary, dtype: float64

In [10]:
nonsense_edu_1 = df.loc[df['Educational Degree'] == '1 - Basic', 'Age']
nonsense_edu_1.nsmallest(1)

659    15.0
Name: Age, dtype: float64

In [11]:
nonsense_edu_2 = df.loc[df['Educational Degree'] == '2 - High School', 'Age']
nonsense_edu_2.nsmallest(1)

695    18.0
Name: Age, dtype: float64

In [12]:
nonsense_edu_3 = df.loc[df['Educational Degree'] == '3 - BSc/MSc', 'Age']
nonsense_edu_3.nsmallest(1)

381    20.0
Name: Age, dtype: float64

In [13]:
nonsense_edu_4 = df.loc[df['Educational Degree'] == '4 - PhD' , 'Age']
nonsense_edu_4.nsmallest(1)

4122    23.0
Name: Age, dtype: float64

In [14]:
nonsense_motor = df.loc[df['Age'] < 16, 'Premiums in LOB: Motor']
nonsense_motor

659      46.23
689      54.90
865      40.34
1436    129.58
2579     48.23
3146     60.68
4465     28.56
4483     43.34
5347    148.14
5607     43.23
8962     19.56
9906     69.68
Name: Premiums in LOB: Motor, dtype: float64

In [15]:
nonsense_house = df.loc[df['Age'] < 16, 'Premiums in LOB: Household']
nonsense_house

659     1079.65
689      406.20
865      847.95
1436     177.80
2579     396.75
3146     270.60
4465    1359.15
4483     589.55
5347     628.45
5607     690.70
8962    1109.10
9906     231.15
Name: Premiums in LOB: Household, dtype: float64

In [16]:
nonsense_work = df.loc[df['Age'] < 16, 'Premiums in LOB: Work Compensations']
nonsense_work

659     -10.00
689     256.05
865     112.13
1436    218.15
2579     24.45
3146    107.13
4465    179.59
4483    179.48
5347     30.23
5607    142.25
8962     53.90
9906     82.35
Name: Premiums in LOB: Work Compensations, dtype: float64

In [17]:
nonsense_child = df.loc[df['Age'] < 16, 'Has Children (Y=1)']
nonsense_child

659     1.0
689     1.0
865     1.0
1436    0.0
2579    0.0
3146    1.0
4465    0.0
4483    1.0
5347    1.0
5607    0.0
8962    0.0
9906    1.0
Name: Has Children (Y=1), dtype: float64

In [18]:
fpy_before_by = df.loc[df['First Policy´s Year'] < df['Brithday Year']]
fpy_before_by

,Customer Identity,First Policy´s Year,Brithday Year,Educational Degree,Gross Monthly Salary,Geographic Living Area,Has Children (Y=1),Customer Monetary Value,Claims Rate,Premiums in LOB: Motor,Premiums in LOB: Household,Premiums in LOB: Health,Premiums in LOB: Life,Premiums in LOB: Work Compensations,Age
1,2,1981.0,1995.0,2 - High School,677.0,4.0,1.0,-131.13,1.12,77.46,416.20,116.69,194.48,106.13,21.0
13,14,1983.0,2000.0,1 - Basic,1043.0,3.0,1.0,-75.12,1.06,44.34,342.85,127.69,267.94,94.46,16.0
18,19,1981.0,1982.0,1 - Basic,1414.0,3.0,1.0,230.38,0.71,313.17,373.40,121.80,14.78,72.57,34.0
22,23,1976.0,1986.0,2 - High School,1495.0,1.0,1.0,-89.79,1.08,209.04,308.95,192.48,64.79,54.90,30.0
40,41,1994.0,1995.0,2 - High School,1177.0,4.0,1.0,121.36,0.84,52.01,455.65,135.47,146.36,148.03,21.0
44,45,1985.0,1990.0,3 - BSc/MSc,1065.0,1.0,1.0,-128.68,1.19,111.80,-35.00,208.26,224.71,44.23,26.0
46,47,1976.0,1986.0,3 - BSc/MSc,1219.0,4.0,1.0,-94.90,1.08,269.94,300.60,143.25,59.79,69.90,30.0
71,72,1985.0,1989.0,3 - BSc/MSc,1159.0,4.0,1.0,195.82,0.72,150.03,236.70,286.61,70.79,33.23,27.0
95,96,1976.0,1986.0,3 - BSc/MSc,2668.0,4.0,1.0,-25.00,1.00,296.50,70.00,200.15,60.79,8.67,30.0
105,106,1986.0,1988.0,3 - BSc/MSc,2019.0,4.0,1.0,-2.65,0.97,89.24,82.25,408.41,19.56,40.34,28.0
108,109,1991.0,1995.0,1 - Basic,764.0,4.0,1.0,71.24,0.93,79.68,912.95,97.24,213.04,16.56,21.0
134,135,1976.0,1977.0,4 - PhD,1810.0,2.0,1.0,543.21,0.14,490.98,79.45,86.35,-1.11,3.89,39.0
142,143,1984.0,1986.0,4 - PhD,1266.0,2.0,1.0,210.71,0.66,213.04,138.35,287.50,19.56,42.23,30.0
145,146,1983.0,1986.0,1 - Basic,2554.0,1.0,1.0,-96.11,1.12,144.36,-11.10,381.85,47.23,12.78,30.0
149,150,1989.0,1994.0,1 - Basic,984.0,4.0,1.0,255.71,0.63,64.90,197.25,29.56,18.56,451.53,22.0
151,152,1977.0,1984.0,2 - High School,1146.0,3.0,1.0,433.97,0.48,165.03,358.95,241.38,6.89,106.91,32.0
152,153,1981.0,1989.0,2 - High School,1753.0,4.0,0.0,10.34,0.97,125.80,785.70,79.57,136.47,101.13,27.0
155,156,1986.0,1992.0,3 - BSc/MSc,1354.0,3.0,0.0,589.33,0.43,100.13,614.55,321.84,-0.11,48.23,24.0
161,162,1975.0,1977.0,3 - BSc/MSc,2285.0,1.0,0.0,471.21,0.25,349.40,87.80,142.47,9.78,68.79,39.0
168,169,1977.0,1997.0,2 - High School,927.0,4.0,1.0,205.16,0.72,158.03,313.40,245.38,93.13,9.89,19.0
186,187,1993.0,1999.0,1 - Basic,1247.0,2.0,1.0,-128.24,1.07,33.23,1026.30,82.57,75.68,212.15,17.0
205,206,1976.0,1983.0,2 - High School,1968.0,3.0,1.0,328.73,0.46,343.62,63.90,170.81,30.34,40.45,33.0
219,220,1985.0,1993.0,2 - High School,1342.0,4.0,1.0,31.01,0.93,189.59,240.60,249.38,56.01,63.90,23.0
227,228,1981.0,1982.0,2 - High School,1607.0,4.0,1.0,807.72,0.00,333.95,323.40,84.35,44.12,46.90,34.0
234,235,1991.0,1996.0,1 - Basic,1980.0,2.0,1.0,-13.33,0.99,33.34,406.20,131.69,175.70,164.03,20.0
241,242,1983.0,1986.0,2 - High School,642.0,4.0,1.0,381.53,0.49,188.48,273.95,271.83,26.45,29.45,30.0
245,246,1984.0,1993.0,1 - Basic,566.0,3.0,1.0,-20.55,1.00,32.23,422.30,302.50,101.24,73.46,23.0
251,252,1978.0,1980.0,3 - BSc/MSc,1920.0,4.0,1.0,-25.00,1.00,389.63,68.90,154.25,17.67,23.67,36.0
257,258,1991.0,1995.0,3 - BSc/MSc,380.0,1.0,0.0,1105.42,0.21,50.90,1012.40,221.93,10.78,128.80,21.0
259,260,1984.0,1986.0,4 - PhD,1201.0,4.0,1.0,455.97,0.35,291.61,162.80,230.71,26.56,29.67,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10164,10165,1986.0,1997.0,2 - High School,1026.0,4.0,1.0,-130.91,1.09,78.35,829.60,134.47,148.14,36.12,19.0
10170,10171,1980.0,1989.0,3 - BSc/MSc,1872.0,2.0,1.0,440.31,0.36,263.05,181.70,217.04,19.56,40.12,27.0
10173,10174,1976.0,1990.0,3 - BSc/MSc,1274.0,4.0,1.0,406.75,0.54,162.81,431.75,257.27,25.56,52.01,26.0
10186,10187,1980.0,1994.0,3 - BSc/MSc,1437.0,1.0,1.0,115.25,0.78,225.60,68.90,195.26,92.35,47.90,22.0
10187,10188,1979.0,1985.0,2 - High School,2044.0,1.0,1.0,26.55,0.92,92.24,104.45,240.60,97.13,145.14,31.0
10188,10189,1978.0,1993.0,1 - Basic,967.0,3.0,1.0,929.51,0.34,19.45,1085.20,83.35,65.79,196.48,23.0
10189,10190,1986.0,1996.0,2 - High School,1589.0,4.0,1.0,-62.34,1.04,126.58,536.20,204.26,99.02,64.90,20.0
10205,10206,1989.0,1994.0,1 - Basic,356.0,4.0,1.0,-210.37,1.15,35.45,766.80,73.68,150.14,185.37,22.0
10206,10207,1996.0,1998.0,1 - Basic,794.0,4.0,1.0,655.46,0.32,56.90,515.65,260.16,102.02,62.79,18.0
10209,10210,1980.0,1986.0,3 - BSc/MSc,1250.0,3.0,1.0,406.20,0.37,333.73,117.25,168.92,22.56,42.34,30.0
10216,10217,1986.0,1996.0,1 - Basic,970.0,4.0,1.0,901.95,0.36,39.23,1070.20,96.24,182.48,63.01,20.0
10217,10218,1976.0,1987.0,2 - High School,1419.0,1.0,1.0,585.88,0.31,256.38,354.50,234.60,0.89,35.12,29.0
10218,10219,1981.0,1988.0,3 - BSc/MSc,1373.0,4.0,1.0,26.45,0.93,396.41,123.35,103.02,33.45,38.45,28.0
10219,10220,1978.0,1979.0,1 - Basic,2342.0,3.0,1.0,-190.14,1.14,113.80,696.25,166.81,146.36,18.78,37.0
10222,10223,1988.0,1995.0,2 - High School,1686.0,3.0,1.0,610.44,0.42,72.46,654.00,125.58,114.80,133.36,21.0
10227,10228,1977.0,1990.0,3 - BSc/MSc,1177.0,1.0,1.0,-40.78,1.03,379.96,48.90,190.48,-7.00,1.78,26.0
10228,10229,1978.0,1996.0,2 - High School,844.0,3.0,0.0,1041.42,0.25,51.01,1045.75,247.27,53.90,20.67,20.0
10230,10231,1991.0,1996.0,1 - Basic,1594.0,3.0,0.0,1083.11,0.14,42.34,877.40,135.58,89.35,141.36,20.0
10231,10232,1976.0,1997.0,2 - High School,1140.0,3.0,0.0,249.95,0.55,327.73,23.90,178.81,21.56,55.12,19.0
10244,10245,1992.0,1994.0,1 - Basic,1297.0,1.0,1.0,546.33,0.41,41.12,476.20,165.81,193.48,98.35,22.0
10253,10254,1985.0,1995.0,1 - Basic,952.0,1.0,1.0,17.01,0.96,14.56,637.35,134.58,128.47,155.92,21.0
10257,10258,1987.0,1997.0,2 - High School,1017.0,1.0,1.0,-87.22,1.09,149.14,111.70,227.60,129.69,44.23,19.0
10259,10260,1975.0,1985.0,2 - High School,1882.0,1.0,1.0,467.31,0.30,320.17,157.25,170.70,37.34,22.45,31.0
10263,10264,1985.0,1995.0,2 - High School,911.0,3.0,0.0,-68.34,1.07,77.57,83.35,417.08,57.01,13.67,21.0
10267,10268,1977.0,1996.0,1 - Basic,834.0,4.0,1.0,254.72,0.67,181.48,309.50,134.58,114.80,98.24,20.0
10268,10269,1987.0,1988.0,3 - BSc/MSc,1414.0,3.0,1.0,50.46,0.90,129.58,167.80,184.48,165.92,75.46,28.0
10273,10274,1989.0,1992.0,2 - High School,1035.0,1.0,1.0,293.51,0.58,235.71,195.60,103.13,170.92,58.12,24.0
10284,10285,1980.0,1987.0,3 - BSc/MSc,1504.0,4.0,1.0,-1.55,0.96,390.63,29.45,179.70,-6.00,NaN,29.0
10288,10289,1982.0,1993.0,2 - High School,1465.0,1.0,1.0,795.15,0.35,67.79,820.15,102.13,182.48,86.46,23.0
10290,10291,1994.0,1999.0,1 - Basic,626.0,3.0,1.0,176.26,0.85,6.89,878.50,103.13,113.02,201.26,17.0

In [19]:
df.loc[df['Age'] < 16,'Educational Degree']

659     1 - Basic
689     1 - Basic
865     1 - Basic
1436    1 - Basic
2579    1 - Basic
3146    1 - Basic
4465    1 - Basic
4483    1 - Basic
5347    1 - Basic
5607    1 - Basic
8962    1 - Basic
9906    1 - Basic
Name: Educational Degree, dtype: object

In [20]:
df.plot.hist(by = 'Gross Monthly Salary',bins = 500,legend = False)

The data appears to be skewed so we'll replace the missing values with the median

In [24]:
median = df['Gross Monthly Salary'].median()
df_median_replace = df.copy(True)
df_median_replace['Gross Monthly Salary'] = df_median_replace['Gross Monthly Salary'].fillna(median)
descr_median = df_median_replace.describe()
descr_median

,Customer Identity,First Policy´s Year,Brithday Year,Gross Monthly Salary,Geographic Living Area,Has Children (Y=1),Customer Monetary Value,Claims Rate,Premiums in LOB: Motor,Premiums in LOB: Household,Premiums in LOB: Health,Premiums in LOB: Life,Premiums in LOB: Work Compensations,Age
count,10296.00000,10266.000000,10279.000000,10296.000000,10295.000000,10275.000000,10296.000000,10296.000000,10262.000000,10296.000000,10253.000000,10192.000000,10210.000000,10279.000000
mean,5148.50000,1991.062634,1968.007783,2506.648990,2.709859,0.706764,177.892605,0.742772,300.470252,210.431192,171.580833,41.855782,41.277514,47.992217
std,2972.34352,511.267913,19.709476,1155.424192,1.266291,0.455268,1945.811505,2.916964,211.914997,352.595984,296.405976,47.480632,51.513572,19.709476
min,1.00000,1974.000000,1028.000000,333.000000,1.000000,0.000000,-165680.420000,0.000000,-4.110000,-75.000000,-2.110000,-7.000000,-12.000000,15.000000
25%,2574.75000,1980.000000,1953.000000,1708.500000,1.000000,0.000000,-9.440000,0.390000,190.590000,49.450000,111.800000,9.890000,10.670000,33.000000
50%,5148.50000,1986.000000,1968.000000,2501.500000,3.000000,1.000000,186.870000,0.720000,298.610000,132.800000,162.810000,25.560000,25.670000,48.000000
75%,7722.25000,1992.000000,1983.000000,3289.000000,4.000000,1.000000,399.777500,0.980000,408.300000,290.050000,219.820000,57.790000,56.790000,63.000000
max,10296.00000,53784.000000,2001.000000,55215.000000,4.000000,1.000000,11875.890000,256.200000,11604.420000,25048.800000,28272.000000,398.300000,1988.700000,988.000000

In [25]:
descr = df.describe()
descr

,Customer Identity,First Policy´s Year,Brithday Year,Gross Monthly Salary,Geographic Living Area,Has Children (Y=1),Customer Monetary Value,Claims Rate,Premiums in LOB: Motor,Premiums in LOB: Household,Premiums in LOB: Health,Premiums in LOB: Life,Premiums in LOB: Work Compensations,Age
count,10296.00000,10266.000000,10279.000000,10260.000000,10295.000000,10275.000000,10296.000000,10296.000000,10262.000000,10296.000000,10253.000000,10192.000000,10210.000000,10279.000000
mean,5148.50000,1991.062634,1968.007783,2506.667057,2.709859,0.706764,177.892605,0.742772,300.470252,210.431192,171.580833,41.855782,41.277514,47.992217
std,2972.34352,511.267913,19.709476,1157.449634,1.266291,0.455268,1945.811505,2.916964,211.914997,352.595984,296.405976,47.480632,51.513572,19.709476
min,1.00000,1974.000000,1028.000000,333.000000,1.000000,0.000000,-165680.420000,0.000000,-4.110000,-75.000000,-2.110000,-7.000000,-12.000000,15.000000
25%,2574.75000,1980.000000,1953.000000,1706.000000,1.000000,0.000000,-9.440000,0.390000,190.590000,49.450000,111.800000,9.890000,10.670000,33.000000
50%,5148.50000,1986.000000,1968.000000,2501.500000,3.000000,1.000000,186.870000,0.720000,298.610000,132.800000,162.810000,25.560000,25.670000,48.000000
75%,7722.25000,1992.000000,1983.000000,3290.250000,4.000000,1.000000,399.777500,0.980000,408.300000,290.050000,219.820000,57.790000,56.790000,63.000000
max,10296.00000,53784.000000,2001.000000,55215.000000,4.000000,1.000000,11875.890000,256.200000,11604.420000,25048.800000,28272.000000,398.300000,1988.700000,988.000000

In [26]:
mean = df['Gross Monthly Salary'].mean()
df_mean_replace = df.copy(True)
df_mean_replace['Gross Monthly Salary'] = df_mean_replace['Gross Monthly Salary'].fillna(mean)
descr_mean = df_mean_replace.describe()
descr_mean

,Customer Identity,First Policy´s Year,Brithday Year,Gross Monthly Salary,Geographic Living Area,Has Children (Y=1),Customer Monetary Value,Claims Rate,Premiums in LOB: Motor,Premiums in LOB: Household,Premiums in LOB: Health,Premiums in LOB: Life,Premiums in LOB: Work Compensations,Age
count,10296.00000,10266.000000,10279.000000,10296.000000,10295.000000,10275.000000,10296.000000,10296.000000,10262.000000,10296.000000,10253.000000,10192.000000,10210.000000,10279.000000
mean,5148.50000,1991.062634,1968.007783,2506.667057,2.709859,0.706764,177.892605,0.742772,300.470252,210.431192,171.580833,41.855782,41.277514,47.992217
std,2972.34352,511.267913,19.709476,1155.424152,1.266291,0.455268,1945.811505,2.916964,211.914997,352.595984,296.405976,47.480632,51.513572,19.709476
min,1.00000,1974.000000,1028.000000,333.000000,1.000000,0.000000,-165680.420000,0.000000,-4.110000,-75.000000,-2.110000,-7.000000,-12.000000,15.000000
25%,2574.75000,1980.000000,1953.000000,1708.500000,1.000000,0.000000,-9.440000,0.390000,190.590000,49.450000,111.800000,9.890000,10.670000,33.000000
50%,5148.50000,1986.000000,1968.000000,2506.000000,3.000000,1.000000,186.870000,0.720000,298.610000,132.800000,162.810000,25.560000,25.670000,48.000000
75%,7722.25000,1992.000000,1983.000000,3289.000000,4.000000,1.000000,399.777500,0.980000,408.300000,290.050000,219.820000,57.790000,56.790000,63.000000
max,10296.00000,53784.000000,2001.000000,55215.000000,4.000000,1.000000,11875.890000,256.200000,11604.420000,25048.800000,28272.000000,398.300000,1988.700000,988.000000

In [27]:
dif_median = descr_median['Gross Monthly Salary'] - descr['Gross Monthly Salary']
dif_median

count    36.000000
mean     -0.018067
std      -2.025442
min       0.000000
25%       2.500000
50%       0.000000
75%      -1.250000
max       0.000000
Name: Gross Monthly Salary, dtype: float64

In [28]:
dif_mean = descr_mean['Gross Monthly Salary'] - descr['Gross Monthly Salary']
dif_mean

count    3.600000e+01
mean     1.364242e-12
std     -2.025482e+00
min      0.000000e+00
25%      2.500000e+00
50%      4.500000e+00
75%     -1.250000e+00
max      0.000000e+00
Name: Gross Monthly Salary, dtype: float64

In [30]:
edu = df['Educational Degree'].unique()
edu

array(['2 - High School', '1 - Basic', '3 - BSc/MSc', '4 - PhD', nan],
      dtype=object)

In [37]:
edu_counts = df.groupby(['Educational Degree'])['Educational Degree'].count()
edu_counts

Educational Degree
1 - Basic          1272
2 - High School    3510
3 - BSc/MSc        4799
4 - PhD             698
Name: Educational Degree, dtype: int64

In [43]:
fr = []
total = edu_counts.values.sum()
for edu in edu_counts.values:
    freq = edu/total
    fr.append(freq)
fr

[0.12374744624963518,
 0.34147290592470086,
 0.4668742095534585,
 0.06790543827220547]

In [44]:
na_total = df['Educational Degree'].isna().sum()
print(na_total)
fr_na = []
for freq in fr:
    freq_na = na_total * freq
    fr_na.append(freq_na)
fr_na

17

[2.1037065862437982, 5.805039400719915, 7.936861562408795, 1.154392450627493]

Based on this we can say that we will replace the 17 NaN's with 2 1 - Basic 6 2 - High School 8 3 - BSc/MSc and 1 4 - PhD

Notice that 2+6+8+1 = 17 which is the total number of nulls in this column

In [50]:
edu_degree = df['Educational Degree'].replace({'1 - Basic':1,'2 - High School':2,'3 - BSc/MSc':3,'4 - PhD':4})
corr = edu_degree.corr(df['Gross Monthly Salary'])
corr
#doesn't appear to have a strong correlation

0.1500304539129789

In [51]:
corr = edu_degree.corr(df['Geographic Living Area'])
corr
#doesn't appear to have a strong correlation

-0.013689240948516705

In [52]:
corr = edu_degree.corr(df['Customer Monetary Value'])
corr
#doesn't appear to have a strong correlation

-0.01809993471404353

In [63]:
import random
choices = ['1 - Basic','1 - Basic','2 - High School','2 - High School','2 - High School','2 - High School','2 - High School','2 - High School','3 - BSc/MSc','3 - BSc/MSc','3 - BSc/MSc','3 - BSc/MSc','3 - BSc/MSc','3 - BSc/MSc','3 - BSc/MSc','3 - BSc/MSc','4 - PhD']
secure_random = random.SystemRandom()
na_ind = df[df['Educational Degree'].isnull()].index.tolist()
df_edu = df.copy(True)
i = 0
replace = []

for i in na_ind:
    edu = secure_random.choice(choices)
    df_edu['Educational Degree'] = df_edu.iloc[3,i].fillna(edu)

df_edu

IndexError: single positional indexer is out-of-bounds